version: "3.8"

services:
  laravel:
    container_name: laravel
    build:
      context: ./laravel/local
    environment:
      - APP_ENV='local'
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${POSTGRES_DB}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      # 以下の環境変数により、コンテナとドメインを紐づけているらしい
      - VIRTUAL_HOST=api.dev.practice-react-laravel.site
      # Laravelサーバの起動で--portオプションあるが、command: php artisan server --port=8000にすると、ファイルを修正するとエラーになるから80のままで行く
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=api.dev.practice-react-laravel.site
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - web
    volumes:
      - ./laravel/src/laravel-api-practice:/var/www
    depends_on:
      - nginx-proxy

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C
      - TZ=Asia/Tokyo
    volumes:
      - laravel-api-practice-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - web

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: letsencrypt
    # このコンテナはnginx-proxyコンテナと連携してSSL証明書など発行するので、nginx-proxyのvolumeを引き継ぐ
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # nginx-proxyコンテナがこのコンテナで生成した証明書を共有するための設定
      - certs:/etc/nginx/certs
      # 以下のスクリプトがSSL証明書の生成や自動更新を行う→acmeボリュームに保存しておく
      - acme:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: ${LETSENCRYPT_EMAIL}
      ACME_CHALLENGE: DNS-01
      ACMESH_DNS_API_CONFIG: |-
        DNS_API: dns_cf
        CF_Key: ${CLOUDFLARE_API_KEY}
        CF_Email: ${CLOUDFLARE_EMAIL}
    networks:
      - web
    depends_on:
      - nginx-proxy

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    # 以下で8000を公開しなくて良いのは、Mac向けに公開するのは80と443だけでよくて、
    # Dockerコンテナ間でのポートは、つまりwebネットワーク内ではLaravelサーバが8000, Reactサーバが80となっている。
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - web

volumes:
  laravel-api-practice-data:
  acme:
  html:
  certs:
  vhost:
networks:
  web:
    external: true
