have_fun: true
code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: true
    code_review: true
ignore_patterns:
  - composer.json
  - composer.lock
  - package.json
  - package-lock.json
  - README.md
  - .env.example
  - storage/**
